connection: &connection
  adapter: postgresql
  encoding: unicode
  host:     localhost
  pool: 5


development:
  <<: *connection
  database: url-shortener_dev
  username: <%= ENV['APP_POSTGRES_USER'] %>
  password: <%= ENV['APP_POSTGRES_PASSWORD'] %>

test: &test
  <<: *connection
  database: url-shortener_test
  username: <%= ENV['APP_POSTGRES_USER'] %>
  password: <%= ENV['APP_POSTGRES_PASSWORD'] %>

production:
  url: <%= ENV['DATABASE_URL'] %>  